export { registerHealthRoutes } from './health.ts';
export { registerAuthRoutes } from './auth.ts';
export { registerAdminUserRoutes, type AdminUserRouteDeps } from './admin-users.ts';
export { registerCourseRoutes, type CourseRouteDeps } from './courses.ts';
export { registerQuizRoutes } from './quiz.ts';
export { registerSyncRoutes } from './sync.ts';
export { registerAdminCourseRoutes } from './admin-courses.ts';
export { registerEnrollmentRoutes } from './enrollments.ts';
export { registerCohortRoutes, type CohortRouteDeps } from './cohorts.ts';
export { registerDocumentRoutes } from './documents.ts';
