export { registerHealthRoutes } from './health.js';
export { registerAuthRoutes } from './auth.js';
export { registerAdminUserRoutes, type AdminUserRouteDeps } from './admin-users.js';
export { registerCourseRoutes, type CourseRouteDeps } from './courses.js';
export { registerQuizRoutes } from './quiz.js';
export { registerSyncRoutes } from './sync.js';
export { registerAdminCourseRoutes } from './admin-courses.js';
export { registerEnrollmentRoutes } from './enrollments.js';
export { registerDocumentRoutes } from './documents.js';
export { registerInstructorAnalyticsRoutes, type InstructorAnalyticsRouteDeps } from './instructor-analytics.js';
export { registerCertificateRoutes, type CertificateRouteDeps } from './certificates.js';
